---
rooturl: "localhost:8080"
publicport: ":8080"
grpcport: ":8082"
env: "dev"
autotls: false
debug: true
##### External Services
apikeys:
  pwnedkey: ""
  ip2location: ""

#### SCORE
email:
  score:
    disposable:
      yes: 20
      no: 0
    free:
      yes: 20
      no: 0
    spam:
      yes: 30
      no: 0
    valid:
      yes: 0
      no: 40
    generic:
      yes: 12
      no: 0
    catchall:
      yes: 10
      no: 0
    leaked:
      yes: 25
      no: -10
ip:
  score:
    proxy:
      yes: 40
      no: 0
    spam:
      yes: 40
      no: 0
    tor:
      yes: 20
      no: 0
    vpn:
      yes: 15
      no: 0

### SMTP
smtp:
  hostname: ""
  mailaddress: ""
errorreporter:
  default: ""
  airbrakecredentials: ""
proxy:
  cachedurationminutes: 120
  workers: 40

### Database: sqlite3 or postgresql. For Non-Memory SQLite, change host: "db.sqlite3"
database:
  type: "sqlite3"
  Name: ""
  host: "db"
  port: 0
  username: ""
  password: ""
  timezone: "America/Vancouver"
  ssl: false
