---
publicport: ":8080"
grpcport: ":8082"
env: "dev"
autotls: false
debug: true
##### External Services
external:
  maxminddest: "assets/Maxmind/download/"
  ip2location: "assets/IP2Location/download/"

## Rate limit
ratelimit:
  enabled: false
  max: 20 # Max number of recent connections during `Duration` seconds before sending a 429 response
  expiration: 30 # Expiration is the time on how long to keep records of requests in memory per minute

## Crontab (in hours)
crontab:
  vpn: 24
  proxy: 24
  tor: 12
  spam: 24
  maxmind: 24
#### SCORE
email:
  score:
    disposable:
      yes: 20
      no: 0
    free:
      yes: 20
      no: 0
    spam:
      yes: 30
      no: 0
    valid:
      yes: 0
      no: 40
    generic:
      yes: 12
      no: 0
    catchall:
      yes: 10
      no: 0
    leaked:
      yes: 25
      no: -10
    domain:
      week: 30
      month: 20
      year: 10
      yearplus: -10
ip:
  score:
    proxy:
      yes: 40
      no: 0
    spam:
      yes: 40
      no: 0
    tor:
      yes: 20
      no: 0
    vpn:
      yes: 15
      no: 0

### SMTP
smtp:
  hostname: ""
  mailaddress: ""

## error reporting
errorreporter:
  default: ""
  airbrakecredentials: ""

## Proxy Settings
proxy:
  cachedurationminutes: 120
  workers: 40

### Database: sqlite3 or postgresql. For Non-Memory SQLite, change host: "db.sqlite3"
database:
  type: "sqlite3"
  Name: ""
  host: "db"
  port: 0
  username: ""
  password: ""
  timezone: "America/Vancouver"
  ssl: false
