appname: "ThreatDefender"
appversion: "0.2.0"
rooturl: "localhost:8080"
publicport: 8080
serverport: 8081
grpcport: 8082
env: "dev"
autotls: false
debug: true
databasename: "sqlite3"
pwnedkey: ""
smtp:
  hostname: ""
  mailaddress: ""
errorreporter:
  default: ""
  airbrakecredentials: ""
proxy:
  cachedurationminutes: 120
  workers: 40
database:
  host: "db.sqlite3"
  port: 0
  username: ""
  password: ""
  dbname: ""
  timezone: "America/Vancouver"
  ssl: true
