// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: ip.proto

package proto

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetProxyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proxies []*Proxy `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
}

func (x *GetProxyListResponse) Reset() {
	*x = GetProxyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProxyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxyListResponse) ProtoMessage() {}

func (x *GetProxyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxyListResponse.ProtoReflect.Descriptor instead.
func (*GetProxyListResponse) Descriptor() ([]byte, []int) {
	return file_ip_proto_rawDescGZIP(), []int{0}
}

func (x *GetProxyListResponse) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type GetSpamListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spam []*Spam `protobuf:"bytes,1,rep,name=spam,proto3" json:"spam,omitempty"`
}

func (x *GetSpamListResponse) Reset() {
	*x = GetSpamListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpamListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpamListResponse) ProtoMessage() {}

func (x *GetSpamListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpamListResponse.ProtoReflect.Descriptor instead.
func (*GetSpamListResponse) Descriptor() ([]byte, []int) {
	return file_ip_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpamListResponse) GetSpam() []*Spam {
	if x != nil {
		return x.Spam
	}
	return nil
}

type GetTorListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tor []*Tor `protobuf:"bytes,1,rep,name=tor,proto3" json:"tor,omitempty"`
}

func (x *GetTorListResponse) Reset() {
	*x = GetTorListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorListResponse) ProtoMessage() {}

func (x *GetTorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorListResponse.ProtoReflect.Descriptor instead.
func (*GetTorListResponse) Descriptor() ([]byte, []int) {
	return file_ip_proto_rawDescGZIP(), []int{2}
}

func (x *GetTorListResponse) GetTor() []*Tor {
	if x != nil {
		return x.Tor
	}
	return nil
}

type GetVPNListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vpn []*VPN `protobuf:"bytes,1,rep,name=vpn,proto3" json:"vpn,omitempty"`
}

func (x *GetVPNListResponse) Reset() {
	*x = GetVPNListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVPNListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPNListResponse) ProtoMessage() {}

func (x *GetVPNListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPNListResponse.ProtoReflect.Descriptor instead.
func (*GetVPNListResponse) Descriptor() ([]byte, []int) {
	return file_ip_proto_rawDescGZIP(), []int{3}
}

func (x *GetVPNListResponse) GetVpn() []*VPN {
	if x != nil {
		return x.Vpn
	}
	return nil
}

var File_ip_proto protoreflect.FileDescriptor

var file_ip_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64,
	0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x70, 0x6e, 0x5f, 0x64, 0x74, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73,
	0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x73, 0x70, 0x61, 0x6d, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x70, 0x61, 0x6d, 0x52, 0x04, 0x73, 0x70,
	0x61, 0x6d, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x54, 0x6f, 0x72, 0x52, 0x03, 0x74, 0x6f, 0x72,
	0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x50, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x76, 0x70, 0x6e, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x56, 0x50, 0x4e, 0x52, 0x03, 0x76, 0x70, 0x6e, 0x32, 0x85,
	0x02, 0x0a, 0x09, 0x49, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x56, 0x50, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x13, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x50, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ip_proto_rawDescOnce sync.Once
	file_ip_proto_rawDescData = file_ip_proto_rawDesc
)

func file_ip_proto_rawDescGZIP() []byte {
	file_ip_proto_rawDescOnce.Do(func() {
		file_ip_proto_rawDescData = protoimpl.X.CompressGZIP(file_ip_proto_rawDescData)
	})
	return file_ip_proto_rawDescData
}

var file_ip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ip_proto_goTypes = []interface{}{
	(*GetProxyListResponse)(nil), // 0: GetProxyListResponse
	(*GetSpamListResponse)(nil),  // 1: GetSpamListResponse
	(*GetTorListResponse)(nil),   // 2: GetTorListResponse
	(*GetVPNListResponse)(nil),   // 3: GetVPNListResponse
	(*Proxy)(nil),                // 4: Proxy
	(*Spam)(nil),                 // 5: Spam
	(*Tor)(nil),                  // 6: Tor
	(*VPN)(nil),                  // 7: VPN
	(*empty.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_ip_proto_depIdxs = []int32{
	4, // 0: GetProxyListResponse.proxies:type_name -> Proxy
	5, // 1: GetSpamListResponse.spam:type_name -> Spam
	6, // 2: GetTorListResponse.tor:type_name -> Tor
	7, // 3: GetVPNListResponse.vpn:type_name -> VPN
	8, // 4: IPService.GetProxyList:input_type -> google.protobuf.Empty
	8, // 5: IPService.GetSpamList:input_type -> google.protobuf.Empty
	8, // 6: IPService.GetTorList:input_type -> google.protobuf.Empty
	8, // 7: IPService.GetVPNList:input_type -> google.protobuf.Empty
	0, // 8: IPService.GetProxyList:output_type -> GetProxyListResponse
	1, // 9: IPService.GetSpamList:output_type -> GetSpamListResponse
	2, // 10: IPService.GetTorList:output_type -> GetTorListResponse
	3, // 11: IPService.GetVPNList:output_type -> GetVPNListResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ip_proto_init() }
func file_ip_proto_init() {
	if File_ip_proto != nil {
		return
	}
	file_message_proxy_dto_proto_init()
	file_message_spam_dto_proto_init()
	file_message_tor_dto_proto_init()
	file_message_vpn_dto_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProxyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpamListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTorListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVPNListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ip_proto_goTypes,
		DependencyIndexes: file_ip_proto_depIdxs,
		MessageInfos:      file_ip_proto_msgTypes,
	}.Build()
	File_ip_proto = out.File
	file_ip_proto_rawDesc = nil
	file_ip_proto_goTypes = nil
	file_ip_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IPServiceClient is the client API for IPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IPServiceClient interface {
	GetProxyList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetProxyListResponse, error)
	GetSpamList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSpamListResponse, error)
	GetTorList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTorListResponse, error)
	GetVPNList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetVPNListResponse, error)
}

type iPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPServiceClient(cc grpc.ClientConnInterface) IPServiceClient {
	return &iPServiceClient{cc}
}

func (c *iPServiceClient) GetProxyList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetProxyListResponse, error) {
	out := new(GetProxyListResponse)
	err := c.cc.Invoke(ctx, "/IPService/GetProxyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) GetSpamList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetSpamListResponse, error) {
	out := new(GetSpamListResponse)
	err := c.cc.Invoke(ctx, "/IPService/GetSpamList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) GetTorList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTorListResponse, error) {
	out := new(GetTorListResponse)
	err := c.cc.Invoke(ctx, "/IPService/GetTorList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) GetVPNList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetVPNListResponse, error) {
	out := new(GetVPNListResponse)
	err := c.cc.Invoke(ctx, "/IPService/GetVPNList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPServiceServer is the server API for IPService service.
type IPServiceServer interface {
	GetProxyList(context.Context, *empty.Empty) (*GetProxyListResponse, error)
	GetSpamList(context.Context, *empty.Empty) (*GetSpamListResponse, error)
	GetTorList(context.Context, *empty.Empty) (*GetTorListResponse, error)
	GetVPNList(context.Context, *empty.Empty) (*GetVPNListResponse, error)
}

// UnimplementedIPServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIPServiceServer struct {
}

func (*UnimplementedIPServiceServer) GetProxyList(context.Context, *empty.Empty) (*GetProxyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProxyList not implemented")
}
func (*UnimplementedIPServiceServer) GetSpamList(context.Context, *empty.Empty) (*GetSpamListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpamList not implemented")
}
func (*UnimplementedIPServiceServer) GetTorList(context.Context, *empty.Empty) (*GetTorListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTorList not implemented")
}
func (*UnimplementedIPServiceServer) GetVPNList(context.Context, *empty.Empty) (*GetVPNListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVPNList not implemented")
}

func RegisterIPServiceServer(s *grpc.Server, srv IPServiceServer) {
	s.RegisterService(&_IPService_serviceDesc, srv)
}

func _IPService_GetProxyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).GetProxyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IPService/GetProxyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).GetProxyList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_GetSpamList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).GetSpamList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IPService/GetSpamList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).GetSpamList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_GetTorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).GetTorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IPService/GetTorList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).GetTorList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_GetVPNList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).GetVPNList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IPService/GetVPNList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).GetVPNList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _IPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IPService",
	HandlerType: (*IPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProxyList",
			Handler:    _IPService_GetProxyList_Handler,
		},
		{
			MethodName: "GetSpamList",
			Handler:    _IPService_GetSpamList_Handler,
		},
		{
			MethodName: "GetTorList",
			Handler:    _IPService_GetTorList_Handler,
		},
		{
			MethodName: "GetVPNList",
			Handler:    _IPService_GetVPNList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip.proto",
}
