appname: "ThreatScraper"
appversion: "0.0.2"
rooturl: "localhost"
publicport: 8080
serverport: 8081
env: "dev"
disposablefile: "app/data/raw/disposable_email.txt"
debug: true
databasename: "sqlite3"
errorreporter:
  default: ""
  airbrakecredentials: ""
proxy:
  cachedurationminutes: 120
  workers: 40
database:
  host: "db.sqlite3"
  port: 0
  username: ""
  password: ""
  dbname: ""
  timezone: "America/Vancouver"
  ssl: true
