appname: "Threatscaper"
appversion: "1.0"
rooturl: "http://localhost:666"
publicport: 669
serverport: 666
env: "dev"
disposablefile: "app/data/raw/disposable_email.txt"
debug: true
databasename: "postgresql"
errorreporter:
  default: ""
  airbrakecredentials: ""
proxy:
  cachedurationminutes: 120
  workers: 40
database:
  host: "sqlite3://db.sqlite3"
  port: 0
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  timezone: "America/Vancouver"
  ssl: true
