name: Check & test & build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make check
  docker:
    name: Publish to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Version tag
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: domgolonka/foretoken
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Latest tag
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: domgolonka/foretoken
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag_names: true