name: "Close Stale Issues"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    if: github.repository_owner == 'domgolonka'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            Hello contributors!
            I am marking this issue as stale as it has not received any engagement from the community or maintainers a year. That does not imply that the issue has no merit! If you feel strongly about this issue
            - open a PR referencing and resolving the issue;
            - leave a comment on it and discuss ideas how you could contribute towards resolving it;
            - leave a comment and describe in detail why this issue is critical for your use case;
            - open a new issue with updated details and a plan on resolving the issue.
            Thank you 🙏✌️
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,blocking,docs,backlog'
          days-before-stale: 365
          days-before-close: 30
          exempt-milestones: true
          exempt-assignees: true
          only-pr-labels: 'stale'